// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coreApi1.Server.Models;

#nullable disable

namespace coreApi1.Server.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250414055252_sedc")]
    partial class sedc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("coreApi1.Server.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("ntext")
                        .HasColumnName("categoryDescription");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("categoryName")
                        .IsFixedLength();

                    b.HasKey("CategoryId");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("coreApi1.Server.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductDescription")
                        .HasColumnType("ntext")
                        .HasColumnName("productDescription");

                    b.Property<string>("ProductName")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("productName")
                        .IsFixedLength();

                    b.HasKey("ProductId");

                    b.ToTable("product", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
